services:
  database:
    restart: always
    container_name: database
    image: postgres:16.8
    hostname: jogtracker
    ports:
      - "127.0.0.1:5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_USER=$PGUSER
      - POSTGRES_DB=$PGDATABASE

  jog-backend:
    restart: always
    container_name: jog-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8005:80"
    env_file:
      - .env
    volumes:
      - .:/backend
      - ./static:/backend/static
      - ./media:/backend/media

  jog-redis:
    container_name: jog-redis
    restart: always
    image: redis:7.0.15
    hostname: redis-db
    ports:
      - "127.0.0.1:6380:6379"

  jog-celery:
    restart: always
    container_name: jog-celery
    build:
      context: ./
      dockerfile: celery.Dockerfile
    env_file:
      - .env
    volumes:
      - .:/backend

volumes:
  postgres_data:
