# Generated by Django 5.0.6 on 2024-06-30 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogging_tracker', '0003_weeklyreport_jog_weekly_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jog',
            name='weekly_report',
        ),
    ]
